name: Run benchmarks

on:
  workflow_dispatch:
    inputs:
      test_run:
        description: Should run a quick benchmark round
        default: '0'
        type: choice
        options:
          - '0'
          - '1'

jobs:
  run-benchmarks:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          # Not using variables to allow running from forks
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Run all benchmarks
        env:
          TEST_RUN: ${{ inputs.test_run }}
        run: ./gradlew runAllBenchmarks --no-daemon

      - name: Upload benchmark data
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-data
          path: build/reports/jmh