name: Build benchmark site

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          # Not using variables to allow running from forks
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Download latest benchmark data
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: benchmark.yml
          branch: master
          name: benchmark-data
          path: build/reports/jmh

      - name: Build site
        run: ./gradlew buildSite --no-daemon

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/site

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4